// Bibdle word list — five-letter Bible-related words (names, places, themes).
// All uppercase, all exactly 5 letters. Hand-curated vocabulary, not text
// copied from any copyrighted Bible translation. 366 words — one for every
// day of the year, including leap years, before the cycle repeats.
const ANSWERS = [
  "DAVID", "MOSES", "AARON", "JONAH", "SARAH", "JACOB", "PETER", "JAMES",
  "JESUS", "ISAAC", "NAOMI", "LABAN", "CALEB", "SIMON", "JUDAS", "SILAS",
  "TITUS", "ENOCH", "DINAH", "HAGAR", "HEROD", "LYDIA", "BARAK", "JESSE",
  "HAMAN", "CYRUS", "HOSEA", "URIAH", "MICAH", "NAHUM", "ASHER", "ELIAS",
  "REHUM", "ELIAB", "ELIHU", "AMASA", "ABNER", "ANNAS", "PHEBE", "ORPAH",
  "ACHAN", "ABDON", "AMNON", "TAMAR", "JOASH", "DEMAS", "LINUS", "GAIUS",
  "JASON", "JUDAH", "SINAI", "EGYPT", "SODOM", "SYRIA", "HARAN", "SHEBA",
  "BABEL", "CRETE", "MALTA", "JOPPA", "SIDON", "AMMON", "NEGEV", "JUDEA",
  "KEDAR", "GERAR", "HAZOR", "BEZEK", "MEDIA", "LYDDA", "BEREA", "DERBE",
  "TROAS", "ASSOS", "CHIOS", "SAMOS", "GRACE", "FAITH", "MANNA", "ALTAR",
  "TORAH", "PSALM", "EXILE", "CROWN", "BLOOD", "TRIBE", "REIGN", "HONOR",
  "GLORY", "WORLD", "LIGHT", "BREAD", "WATER", "STONE", "SWORD", "CURSE",
  "RULER", "REBEL", "ANGEL", "JUDGE", "PEACE", "TEMPT", "DEATH", "BEAST",
  "CHILD", "EARTH", "HEART", "SOUTH", "NORTH", "PRIDE", "TRUTH", "SPEAR",
  "FLESH", "SHEEP", "MERCY", "TITHE", "FEAST", "TRIAL", "SAINT", "CHOIR",
  "VOICE", "BLESS", "DEMON", "IDOLS", "ELDER", "OFFER", "DREAM", "CUBIT",
  "LAMBS", "GOATS", "FLOCK", "FLOOD", "STORM", "RAINS", "SLAVE", "BONDS",
  "FREED", "QUAIL", "MOUNT", "RIVER", "OCEAN", "WHALE", "SNAKE", "FRUIT",
  "SEEDS", "WHEAT", "GRAIN", "OLIVE", "GRAPE", "HONEY", "ROBES", "CLOAK",
  "TUNIC", "STAFF", "ARMOR", "TENTS", "WORDS", "BOOKS", "NAMES", "SIGNS",
  "POWER", "MIGHT", "HANDS", "HEALS", "BLIND", "LEPER", "RISEN", "TOMBS",
  "CROSS", "NAILS", "THORN", "CRIED", "MOURN", "HYMNS", "GUILT", "SHAME",
  "WRATH", "ANGER", "FEARS", "HOPES", "LOVED", "LOVES", "KINGS", "QUEEN",
  "REALM", "PROUD", "FOOLS", "TRUST", "CLEAN", "WIDOW", "BRIDE", "GROOM",
  "UNCLE", "ALPHA", "TWINS", "YOUTH", "ADULT", "WIVES", "MOUTH", "TEETH",
  "KNEES", "TEARS", "WOUND", "MAGIC", "CLOUD", "WINDS", "STARS", "HILLS",
  "ROCKS", "SANDS", "TREES", "FIELD", "PLAIN", "CLIFF", "CAVES", "FROST",
  "ISLES", "SHORE", "BROOK", "POOLS", "OMEGA", "PEAKS", "MAGOG", "WOODS",
  "GROVE", "SEVEN", "THREE", "FORTY", "NIGHT", "YEARS", "MONTH", "WEEKS",
  "TODAY", "FIRST", "TENTH", "SIXTY", "FIFTY", "NINTH", "SIXTH", "FIFTH",
  "THIRD", "HOURS", "TIMES", "DAILY", "GREED", "MOCKS", "KINDS", "LOYAL",
  "PULSE", "WEARY", "RIGHT", "WRONG", "NOBLE", "LUSTS", "EAGER", "FAINT",
  "FASTS", "VOWED", "MAKER", "SAVED", "SAVES", "ATONE", "WEEPS", "BOWED",
  "GIVES", "GIFTS", "HARPS", "LAMPS", "MYRRH", "JEWEL", "RINGS", "CHAIN",
  "YOKES", "VEILS", "TOWER", "WALLS", "GATES", "DOORS", "ROOMS", "HOUSE",
  "BOWLS", "WICKS", "SPICE", "LINEN", "CLOTH", "SEALS", "COINS", "MONEY",
  "PURSE", "WHIPS", "BRICK", "BEAMS", "HOOKS", "SHIPS", "BOATS", "SAILS",
  "WAVES", "ROADS", "PATHS", "CAMPS", "WELLS", "BANKS", "LIONS", "BEARS",
  "MULES", "CAMEL", "HORSE", "DOVES", "EAGLE", "RAVEN", "FROGS", "GNATS",
  "FLIES", "WORMS", "BULLS", "SWINE", "FOXES", "VIPER", "MOTHS", "HAWKS",
  "STORK", "WHITE", "BLACK", "GREEN", "IVORY", "BRASS", "AMBER", "DEEDS",
  "WORKS", "TOILS", "LABOR", "IMAGE", "SONGS", "DANCE", "RULES", "COURT",
  "OATHS", "ASKED", "FOUND", "TEACH", "LEADS", "GUIDE", "WALKS", "SPEAK",
  "SPOKE", "SHOUT", "SINGS", "WATCH", "GUARD", "ARISE", "DWELL", "ABIDE",
  "ENTER", "SERVE", "SEEKS", "FINDS", "KNOCK", "OPENS", "BUILT", "BUILD",
  "RAISE", "FALLS", "RISES", "STAND", "SHINE", "ORDER",
];

// Where each word appears in the Bible — the best-known/most recognizable
// occurrence, cited as book/chapter/verse only (never quoted verse text,
// so this is copyright-safe regardless of translation). Best-effort: a
// handful of entries reflect classic KJV wording (marked "(KJV)") for
// words/spellings not used in more modern translations. Shown after a
// round ends; not exhaustive — most of these words appear elsewhere too.
const REFERENCES = {
  DAVID: "1 Samuel 17:50",
  MOSES: "Exodus 14:21",
  AARON: "Exodus 4:14",
  JONAH: "Jonah 1:17",
  SARAH: "Genesis 21:2",
  JACOB: "Genesis 32:28",
  PETER: "Matthew 16:18",
  JAMES: "Matthew 4:21",
  JESUS: "Matthew 1:21",
  ISAAC: "Genesis 22:9",
  NAOMI: "Ruth 1:16",
  LABAN: "Genesis 29:25",
  CALEB: "Numbers 13:30",
  SIMON: "Matthew 4:18",
  JUDAS: "Matthew 26:15",
  SILAS: "Acts 16:25",
  TITUS: "Titus 1:5",
  ENOCH: "Genesis 5:24",
  DINAH: "Genesis 34:1",
  HAGAR: "Genesis 16:1",
  HEROD: "Matthew 2:16",
  LYDIA: "Acts 16:14",
  BARAK: "Judges 4:6",
  JESSE: "1 Samuel 16:1",
  HAMAN: "Esther 3:6",
  CYRUS: "Ezra 1:1",
  HOSEA: "Hosea 1:2",
  URIAH: "2 Samuel 11:15",
  MICAH: "Micah 6:8",
  NAHUM: "Nahum 1:1",
  ASHER: "Genesis 30:13",
  ELIAS: "Matthew 17:3 (KJV)",
  REHUM: "Ezra 4:8",
  ELIAB: "1 Samuel 16:6",
  ELIHU: "Job 32:2",
  AMASA: "2 Samuel 17:25",
  ABNER: "2 Samuel 3:27",
  ANNAS: "John 18:13",
  PHEBE: "Romans 16:1",
  ORPAH: "Ruth 1:14",
  ACHAN: "Joshua 7:1",
  ABDON: "Judges 12:13",
  AMNON: "2 Samuel 13:1",
  TAMAR: "Genesis 38:6",
  JOASH: "2 Kings 11:21",
  DEMAS: "2 Timothy 4:10",
  LINUS: "2 Timothy 4:21",
  GAIUS: "Romans 16:23",
  JASON: "Acts 17:5",
  JUDAH: "Genesis 49:10",
  SINAI: "Exodus 19:20",
  EGYPT: "Exodus 12:31",
  SODOM: "Genesis 19:24",
  SYRIA: "2 Kings 5:1",
  HARAN: "Genesis 11:31",
  SHEBA: "1 Kings 10:1",
  BABEL: "Genesis 11:9",
  CRETE: "Titus 1:5",
  MALTA: "Acts 28:1",
  JOPPA: "Jonah 1:3",
  SIDON: "Matthew 11:21",
  AMMON: "Genesis 19:38",
  NEGEV: "Genesis 12:9",
  JUDEA: "Luke 2:4",
  KEDAR: "Psalm 120:5",
  GERAR: "Genesis 20:1",
  HAZOR: "Joshua 11:10",
  BEZEK: "Judges 1:4",
  MEDIA: "Esther 1:3",
  LYDDA: "Acts 9:32",
  BEREA: "Acts 17:11",
  DERBE: "Acts 14:20",
  TROAS: "Acts 16:9",
  ASSOS: "Acts 20:13",
  CHIOS: "Acts 20:15",
  SAMOS: "Acts 20:15",
  GRACE: "Ephesians 2:8",
  FAITH: "Hebrews 11:1",
  MANNA: "Exodus 16:15",
  ALTAR: "Genesis 8:20",
  TORAH: "Nehemiah 8:1",
  PSALM: "Psalm 23:1",
  EXILE: "2 Kings 25:21",
  CROWN: "2 Timothy 4:8",
  BLOOD: "Exodus 12:13",
  TRIBE: "Revelation 7:4",
  REIGN: "Revelation 11:15",
  HONOR: "Exodus 20:12",
  GLORY: "Isaiah 6:3",
  WORLD: "John 3:16",
  LIGHT: "Genesis 1:3",
  BREAD: "John 6:35",
  WATER: "John 4:14",
  STONE: "1 Samuel 17:49",
  SWORD: "Matthew 26:52",
  CURSE: "Genesis 3:14",
  RULER: "John 3:1",
  REBEL: "Numbers 14:9",
  ANGEL: "Luke 1:26",
  JUDGE: "Judges 4:4",
  PEACE: "John 14:27",
  TEMPT: "Matthew 4:1",
  DEATH: "1 Corinthians 15:55",
  BEAST: "Revelation 13:1",
  CHILD: "Isaiah 9:6",
  EARTH: "Genesis 1:1",
  HEART: "Proverbs 3:5",
  SOUTH: "Acts 8:26",
  NORTH: "Jeremiah 1:14",
  PRIDE: "Proverbs 16:18",
  TRUTH: "John 14:6",
  SPEAR: "John 19:34",
  FLESH: "John 1:14",
  SHEEP: "John 10:11",
  MERCY: "Luke 6:36",
  TITHE: "Malachi 3:10",
  FEAST: "Exodus 12:14",
  TRIAL: "James 1:2",
  SAINT: "Ephesians 1:1",
  CHOIR: "Nehemiah 12:31",
  VOICE: "John 10:27",
  BLESS: "Numbers 6:24",
  DEMON: "Mark 5:9",
  IDOLS: "Exodus 20:4",
  ELDER: "Titus 1:5",
  OFFER: "Genesis 22:2",
  DREAM: "Genesis 37:5",
  CUBIT: "Genesis 6:15",
  LAMBS: "John 21:15",
  GOATS: "Matthew 25:32",
  FLOCK: "Luke 12:32",
  FLOOD: "Genesis 7:17",
  STORM: "Mark 4:39",
  RAINS: "Matthew 7:25",
  SLAVE: "Galatians 3:28",
  BONDS: "Acts 16:26",
  FREED: "Romans 6:18",
  QUAIL: "Exodus 16:13",
  MOUNT: "Matthew 5:1",
  RIVER: "Revelation 22:1",
  OCEAN: "Psalm 104:25",
  WHALE: "Matthew 12:40 (KJV)",
  SNAKE: "Genesis 3:1",
  FRUIT: "Genesis 3:6",
  SEEDS: "Matthew 13:3",
  WHEAT: "Matthew 13:25",
  GRAIN: "Ruth 2:2",
  OLIVE: "Genesis 8:11",
  GRAPE: "Numbers 13:23",
  HONEY: "Exodus 3:8",
  ROBES: "Revelation 7:14",
  CLOAK: "Matthew 5:40",
  TUNIC: "John 19:23",
  STAFF: "Exodus 4:2",
  ARMOR: "Ephesians 6:11",
  TENTS: "Genesis 25:27",
  WORDS: "Matthew 24:35",
  BOOKS: "John 21:25",
  NAMES: "Revelation 21:12",
  SIGNS: "John 20:30",
  POWER: "Acts 1:8",
  MIGHT: "Deuteronomy 6:5",
  HANDS: "Luke 23:46",
  HEALS: "Psalm 147:3",
  BLIND: "John 9:25",
  LEPER: "Mark 1:40",
  RISEN: "Luke 24:6",
  TOMBS: "Matthew 27:52",
  CROSS: "Luke 9:23",
  NAILS: "John 20:25",
  THORN: "Matthew 27:29",
  CRIED: "Mark 15:34",
  MOURN: "Matthew 5:4",
  HYMNS: "Matthew 26:30",
  GUILT: "Psalm 32:5",
  SHAME: "Genesis 2:25",
  WRATH: "Romans 1:18",
  ANGER: "Ephesians 4:26",
  FEARS: "Psalm 34:4",
  HOPES: "Romans 15:13",
  LOVED: "John 3:16",
  LOVES: "John 14:21",
  KINGS: "Revelation 19:16",
  QUEEN: "1 Kings 10:1",
  REALM: "Daniel 6:3 (KJV)",
  PROUD: "James 4:6",
  FOOLS: "Proverbs 1:7",
  TRUST: "Proverbs 3:5",
  CLEAN: "Matthew 23:26",
  WIDOW: "Luke 21:2",
  BRIDE: "Revelation 21:2",
  GROOM: "John 3:29",
  UNCLE: "Jeremiah 32:7",
  ALPHA: "Revelation 1:8",
  TWINS: "Genesis 25:24",
  YOUTH: "1 Timothy 4:12",
  ADULT: "1 Corinthians 13:11",
  WIVES: "Genesis 4:19",
  MOUTH: "Matthew 4:4",
  TEETH: "Matthew 8:12",
  KNEES: "1 Kings 19:18",
  TEARS: "Psalm 56:8",
  WOUND: "Isaiah 53:5",
  MAGIC: "Acts 8:9",
  CLOUD: "Exodus 13:21",
  WINDS: "Matthew 7:27",
  STARS: "Genesis 15:5",
  HILLS: "Psalm 121:1",
  ROCKS: "Matthew 27:51",
  SANDS: "Matthew 7:26",
  TREES: "Genesis 1:11",
  FIELD: "Matthew 13:44",
  PLAIN: "Genesis 11:2",
  CLIFF: "Luke 4:29",
  CAVES: "Judges 6:2",
  FROST: "Exodus 16:14",
  ISLES: "Isaiah 42:4 (KJV)",
  SHORE: "John 21:4",
  BROOK: "1 Kings 17:3 (KJV)",
  POOLS: "John 5:2",
  OMEGA: "Revelation 1:8",
  PEAKS: "Song of Songs 4:8",
  MAGOG: "Revelation 20:8",
  WOODS: "1 Samuel 14:25",
  GROVE: "Genesis 21:33 (KJV)",
  SEVEN: "Genesis 7:2",
  THREE: "Jonah 1:17",
  FORTY: "Genesis 7:12",
  NIGHT: "Genesis 1:5",
  YEARS: "Genesis 15:13",
  MONTH: "Exodus 12:2",
  WEEKS: "Daniel 9:24",
  TODAY: "Luke 2:11",
  FIRST: "Matthew 22:38",
  TENTH: "Leviticus 27:32",
  SIXTY: "Song of Songs 3:7",
  FIFTY: "Genesis 18:24",
  NINTH: "Matthew 27:45",
  SIXTH: "Luke 1:26",
  FIFTH: "Genesis 1:23",
  THIRD: "John 2:1",
  HOURS: "John 11:9",
  TIMES: "Matthew 18:22",
  DAILY: "Matthew 6:11",
  GREED: "Luke 12:15",
  MOCKS: "Proverbs 3:34",
  KINDS: "Genesis 1:21",
  LOYAL: "Ruth 1:16",
  PULSE: "Daniel 1:12 (KJV)",
  WEARY: "Isaiah 40:31",
  RIGHT: "Genesis 18:25",
  WRONG: "1 Corinthians 13:5",
  NOBLE: "Philippians 4:8",
  LUSTS: "2 Timothy 2:22",
  EAGER: "Galatians 2:10",
  FAINT: "Genesis 25:29 (KJV)",
  FASTS: "Zechariah 8:19",
  VOWED: "Genesis 28:20",
  MAKER: "Job 4:17",
  SAVED: "Romans 10:9",
  SAVES: "Psalm 34:18",
  ATONE: "Leviticus 17:11",
  WEEPS: "John 11:35",
  BOWED: "Genesis 43:28",
  GIVES: "James 1:5",
  GIFTS: "Matthew 2:11",
  HARPS: "Psalm 137:2",
  LAMPS: "Matthew 25:1",
  MYRRH: "Matthew 2:11",
  JEWEL: "Proverbs 20:15",
  RINGS: "Exodus 25:12",
  CHAIN: "Genesis 41:42",
  YOKES: "Jeremiah 28:13",
  VEILS: "Exodus 34:33",
  TOWER: "Genesis 11:4",
  WALLS: "Joshua 6:20",
  GATES: "Matthew 16:18",
  DOORS: "John 20:19",
  ROOMS: "John 14:2",
  HOUSE: "Matthew 7:24",
  BOWLS: "Revelation 16:1",
  WICKS: "Matthew 12:20",
  SPICE: "Song of Songs 4:14",
  LINEN: "Luke 23:53",
  CLOTH: "Mark 2:21",
  SEALS: "Revelation 5:1",
  COINS: "Luke 15:8",
  MONEY: "Matthew 6:24",
  PURSE: "Luke 10:4",
  WHIPS: "John 2:15",
  BRICK: "Exodus 1:14",
  BEAMS: "Matthew 7:3 (KJV)",
  HOOKS: "Amos 4:2",
  SHIPS: "1 Kings 9:26",
  BOATS: "Luke 5:2",
  SAILS: "Isaiah 33:23",
  WAVES: "Matthew 14:24",
  ROADS: "Isaiah 40:3",
  PATHS: "Proverbs 3:6",
  CAMPS: "Numbers 2:2",
  WELLS: "Genesis 26:18",
  BANKS: "Joshua 4:18",
  LIONS: "Daniel 6:16",
  BEARS: "2 Kings 2:24",
  MULES: "2 Samuel 13:29",
  CAMEL: "Matthew 19:24",
  HORSE: "Revelation 6:2",
  DOVES: "Matthew 10:16",
  EAGLE: "Exodus 19:4",
  RAVEN: "Genesis 8:7",
  FROGS: "Exodus 8:6",
  GNATS: "Exodus 8:16",
  FLIES: "Exodus 8:21",
  WORMS: "Acts 12:23",
  BULLS: "Psalm 22:12",
  SWINE: "Matthew 8:32 (KJV)",
  FOXES: "Luke 9:58",
  VIPER: "Acts 28:3",
  MOTHS: "Matthew 6:19",
  HAWKS: "Leviticus 11:16",
  STORK: "Leviticus 11:19",
  WHITE: "Revelation 1:14",
  BLACK: "Revelation 6:5",
  GREEN: "Psalm 23:2",
  IVORY: "1 Kings 10:18",
  BRASS: "Revelation 1:15 (KJV)",
  AMBER: "Ezekiel 1:4 (KJV)",
  DEEDS: "Matthew 5:16",
  WORKS: "Ephesians 2:10",
  TOILS: "Ecclesiastes 2:11",
  LABOR: "1 Corinthians 15:58",
  IMAGE: "Genesis 1:27",
  SONGS: "Psalm 137:3",
  DANCE: "Exodus 15:20",
  RULES: "Colossians 2:20",
  COURT: "Acts 25:10",
  OATHS: "Matthew 5:34",
  ASKED: "Matthew 20:32",
  FOUND: "Luke 15:6",
  TEACH: "Psalm 25:4",
  LEADS: "Psalm 23:2",
  GUIDE: "Psalm 48:14",
  WALKS: "Proverbs 10:9",
  SPEAK: "Numbers 22:38",
  SPOKE: "Hebrews 1:1",
  SHOUT: "Joshua 6:20",
  SINGS: "Psalm 96:1",
  WATCH: "Matthew 26:41",
  GUARD: "Philippians 4:7",
  ARISE: "Ephesians 5:14 (KJV)",
  DWELL: "Psalm 23:6",
  ABIDE: "John 15:4 (KJV)",
  ENTER: "Matthew 7:13",
  SERVE: "Joshua 24:15",
  SEEKS: "Proverbs 11:27",
  FINDS: "Proverbs 8:35",
  KNOCK: "Revelation 3:20",
  OPENS: "Revelation 3:7",
  BUILT: "1 Kings 6:1",
  BUILD: "Matthew 16:18",
  RAISE: "John 6:40",
  FALLS: "John 12:24",
  RISES: "Ecclesiastes 1:5",
  STAND: "Ephesians 6:13",
  SHINE: "Matthew 5:16",
  ORDER: "Titus 1:5",
};

// Deterministic "word of the day": every visitor on the same UTC calendar
// day gets the same word, with no server/backend involved.
function getTodayIndex() {
  const EPOCH = Date.UTC(2024, 0, 1); // arbitrary fixed epoch
  const now = new Date();
  const today = Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate());
  const daysSinceEpoch = Math.floor((today - EPOCH) / 86400000);
  return ((daysSinceEpoch % ANSWERS.length) + ANSWERS.length) % ANSWERS.length;
}

function getTodayWord() {
  return ANSWERS[getTodayIndex()];
}

function getTodayKey() {
  const now = new Date();
  return `${now.getUTCFullYear()}-${now.getUTCMonth() + 1}-${now.getUTCDate()}`;
}

function getReference(word) {
  return REFERENCES[word] || null;
}
